-- MySQL Script generated by MySQL Workbench
-- qua 20 nov 2019 18:36:14 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hoteldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hoteldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hoteldb` DEFAULT CHARACTER SET utf8 ;
USE `hoteldb` ;

-- -----------------------------------------------------
-- Table `hoteldb`.`tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`tipos` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `nometipo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `valordiaria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoteldb`.`quartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`quartos` (
  `idquartos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipos_idtipo` INT NOT NULL,
  `status` VARCHAR(20) NULL,
  PRIMARY KEY (`idquartos`),
  INDEX `fk_quartos_tipos_idx` (`tipos_idtipo` ASC),
  CONSTRAINT `fk_quartos_tipos`
    FOREIGN KEY (`tipos_idtipo`)
    REFERENCES `hoteldb`.`tipos` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoteldb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`cliente` (
  `cpf` BIGINT NOT NULL,
  `status` VARCHAR(15) NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cep` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoteldb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`funcionario` (
  `cpf` BIGINT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `cargo` VARCHAR(20) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoteldb`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`itens` (
  `iditens` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`iditens`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoteldb`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `valor` DOUBLE NULL,
  `cliente_cpf` BIGINT NOT NULL,
  `quartos_idquartos` INT NOT NULL,
  `datacheckin` DATETIME NULL,
  `datacheckout` DATETIME NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_reserva_cliente1_idx` (`cliente_cpf` ASC),
  INDEX `fk_reserva_quartos1_idx` (`quartos_idquartos` ASC),
  CONSTRAINT `fk_reserva_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `hoteldb`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_quartos1`
    FOREIGN KEY (`quartos_idquartos`)
    REFERENCES `hoteldb`.`quartos` (`idquartos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoteldb`.`fatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoteldb`.`fatura` (
  `idfatura` INT NOT NULL,
  `saldototal` DOUBLE NULL,
  PRIMARY KEY (`idfatura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
